#!/bin/bash
# Generate Failure Report for Clawdbot Orchestrator
# Creates a detailed markdown report when a task fails
set -euo pipefail

usage() {
  cat << EOF
Generate Failure Report

Usage: $(basename "$0") [options]

Options:
  --task DESCRIPTION   Task description (required)
  --log-dir PATH       Path to task log directory (required)
  --state-file PATH    Path to state.json file
  --output PATH        Output file path (default: stdout)
  -h, --help           Show this help

Output:
  Markdown failure report with:
  - Task summary and stats
  - Last blocking issues
  - What was tried
  - Files changed
  - Next steps

Examples:
  $(basename "$0") --task "Fix transcriptor" --log-dir /logs/task_123 --output report.md
EOF
}

TASK=""
LOG_DIR=""
STATE_FILE=""
OUTPUT=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --task) TASK="$2"; shift 2 ;;
    --log-dir) LOG_DIR="$2"; shift 2 ;;
    --state-file) STATE_FILE="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

[[ -z "$TASK" ]] && { echo "ERROR: --task required" >&2; exit 1; }
[[ -z "$LOG_DIR" ]] && { echo "ERROR: --log-dir required" >&2; exit 1; }

# Try to find state file if not provided
if [[ -z "$STATE_FILE" && -f "$LOG_DIR/state.json" ]]; then
  STATE_FILE="$LOG_DIR/state.json"
fi

# Extract stats from state file
OPENCODE_ITERS="?"
CLAUDE_ITERS="?"
BRANCH="unknown"
WORKTREE_PATH="unknown"
PROJECT_NAME="unknown"

if [[ -n "$STATE_FILE" && -f "$STATE_FILE" ]]; then
  OPENCODE_ITERS=$(jq -r '.opencode_iterations // "?"' "$STATE_FILE" 2>/dev/null)
  CLAUDE_ITERS=$(jq -r '.claude_iterations // "?"' "$STATE_FILE" 2>/dev/null)
  BRANCH=$(jq -r '.branch // "unknown"' "$STATE_FILE" 2>/dev/null)
  WORKTREE_PATH=$(jq -r '.worktree // "unknown"' "$STATE_FILE" 2>/dev/null)
  PROJECT_NAME=$(jq -r '.project_name // "unknown"' "$STATE_FILE" 2>/dev/null)
fi

# Get last blocking issues from most recent Codex review
BLOCKING_ISSUES=""
LATEST_REVIEW=$(ls -t "$LOG_DIR/codex/review_"*.json 2>/dev/null | head -1 || true)
if [[ -n "$LATEST_REVIEW" && -f "$LATEST_REVIEW" ]]; then
  BLOCKING_ISSUES=$(jq -r '
    .issues[]? |
    select(.blocking == true or .severity == "critical") |
    "- [\(.severity // "issue")] \(.message // "Unknown issue")" +
    (if .file then "\n  File: \(.file)" + (if .line then ":\(.line)" else "" end) else "" end) +
    (if .suggestion then "\n  Fix: \(.suggestion)" else "" end)
  ' "$LATEST_REVIEW" 2>/dev/null || echo "Unable to parse review")
fi

# Get list of attempts/approaches from iteration logs
ATTEMPTS=""
ITER_COUNT=0
for iter_file in $(ls -t "$LOG_DIR/opencode/iter_"*.json 2>/dev/null | head -5); do
  ((ITER_COUNT++))
  # Try to extract a summary from each iteration
  SUMMARY=$(jq -r '.summary // .message // empty' "$iter_file" 2>/dev/null | head -1 || true)
  if [[ -n "$SUMMARY" ]]; then
    ATTEMPTS+="$ITER_COUNT. $SUMMARY"$'\n'
  fi
done

# Get files changed from git diff
FILES_CHANGED=""
if [[ -n "$WORKTREE_PATH" && -d "$WORKTREE_PATH" ]]; then
  # Validate iterations is a positive number, default to 1
  diff_count=1
  if [[ "$OPENCODE_ITERS" =~ ^[0-9]+$ && "$OPENCODE_ITERS" -gt 0 ]]; then
    diff_count="$OPENCODE_ITERS"
  fi
  FILES_CHANGED=$(cd "$WORKTREE_PATH" 2>/dev/null && git diff --stat "HEAD~${diff_count}..HEAD" 2>/dev/null | head -20 || echo "Unable to get diff")
fi

# Generate the report
generate_report() {
  cat << EOF
# Task Failed: $TASK

## Summary

| Metric | Value |
|--------|-------|
| Project | $PROJECT_NAME |
| Branch | \`$BRANCH\` |
| OpenCode iterations | $OPENCODE_ITERS |
| Claude iterations | $CLAUDE_ITERS |
| Final status | Max iterations reached |

## Last Blocking Issues

${BLOCKING_ISSUES:-"No blocking issues found in logs"}

## What Was Tried

${ATTEMPTS:-"No iteration summaries available"}

## Files Changed

\`\`\`
${FILES_CHANGED:-"No file changes detected"}
\`\`\`

## Worktree Location

\`\`\`
$WORKTREE_PATH
\`\`\`

## Logs Location

\`\`\`
$LOG_DIR
\`\`\`

## Next Steps

1. Review the code changes at: \`$WORKTREE_PATH\`
2. Check detailed logs at: \`$LOG_DIR\`
3. Look at the last Codex review: \`$LATEST_REVIEW\`
4. Consider:
   - Breaking the task into smaller pieces
   - Providing more specific instructions
   - Fixing the blocking issues manually
   - Running with increased iteration limits

---
*Generated by Clawdbot Intelligent Implementer*
EOF
}

# Output report
if [[ -n "$OUTPUT" ]]; then
  mkdir -p "$(dirname "$OUTPUT")"
  generate_report > "$OUTPUT"
  echo "Failure report saved to: $OUTPUT"
else
  generate_report
fi
